### ISSUE TITLE
App screen turns black and hangs during unlock

### ISSUE THREAD

**Issue by zwimer** [beemdevelopment/Aegis#1423]
### Version

3.1

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 6a

### Android version

14

### Steps to reproduce

1. Clear storage & cache and uninstall the app
2. Install the app either via the play store or F-Droid
3. Import the vault backup
4. Enter password
5. Click Ok

### What do you expect to happen?

The app to let me into my 2FA vault

### What happens instead?

If doing initial import:
App goes to the "Aegis has been set up and is ready to go" screen. Tapping the check mark does nothing for about 15 seconds, then the screen turns black and the app hangs.

If opening the app after the initial import:
After entering the password, the screen turns black and the app hangs.

**Comment by zwimer** [comment]
This does not happen every time. Sometimes I am able to unlock the vault; like if I just leave my phone alone for a bit and try again later it might start working out of the blue.

**Comment by zwimer** [comment]
As for backups, I have local-only (no cloud) backups and after any re-import I re-enable "Automatically back up the vault".

**Comment by zwimer** [comment]
One thing that sometimes works. Log in, let it hang. Minimize the app without closing it. Re-open the app.

**Comment by michaelschattgen** [comment]
Thanks for your report! This issue has already been reported with #1342

This bug has been introduced with the Pixel June update and fortunately already been fixed with the July update. Either update your phone or reboot your device to temporarily fix it.

**Comment by sharpsan** [comment]
> Thanks for your report! This issue has already been reported with #1342
> 
> This bug has been introduced with the Pixel June update and fortunately already been fixed with the July update. Either update your phone or reboot your device to temporarily fix it.

Still happening to me on the July patch.  Pixel 8 Pro.

**Comment by zwimer** [comment]
@michaelschattgen I have the July patch, the issue persists.

**Comment by michaelschattgen** [comment]
@sharpsan @zwimer yeah unfortunately the July update didn't fix it after all. As mentioned in the other thread, we rolled out a beta update which contains a workaround for this bug. Feel free to try it!

https://github.com/beemdevelopment/Aegis/issues/1342#issuecomment-2234280722
