### ISSUE TITLE
Google Drive did not initially appear on Export

### ISSUE THREAD

**Issue by JNavas2** [beemdevelopment/Aegis#507]
###### Info

* __Version__: 1.2
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Google Pixel 3a (sargo)
* __Android version and ROM:__ 10 (QQ3A.200605.002)

###### Steps to reproduce

Open Settings » Export » OK » Menu

###### What do you expect to happen?

Show all Storage Access Framework providers, including Google Drive.

###### What happens instead?

Initially, Google Drive did _not_ appear.
It only appeared after I had played with Export/Import a number of times.

**Comment by alexbakker** [comment]
It looks like OneDrive just doesn't support the ACTION_CREATE_DOCUMENT intent for some reason. Reading files is possible, but creating files is not. Are there any other cloud providers that you would have expected to see on export that don't show up? In your screenshot, Google Drive does show up as an option in both cases.

**Comment by JNavas2** [comment]
OneDrive is essential to me, and many other apps _are_ able to save files to OneDrive, including:
- [Google Recorder](https://play.google.com/store/apps/details?id=com.google.android.apps.recorder&hl=en_US)
- [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.full)
- [WiFi Analyzer](https://play.google.com/store/apps/details?id=com.vrem.wifianalyzer)
- [XiiaLive Pro](https://play.google.com/store/apps/details?id=com.android.DroidLivePlayer)

**Comment by alexbakker** [comment]
The apps listed seem to either use the OneDrive API directly or expose files to OneDrive through the [sharing mechanism](https://developer.android.com/training/secure-file-sharing/setup-sharing) in Android. If they were using the Storage Access Framework, OneDrive would also not appear there. If you want, we can consider using the sharing mechanism as a way to export the vault as a new feature request.

**Comment by JNavas2** [comment]
I confirm that [Authenticator Pro](https://play.google.com/store/apps/details?id=me.jmh.authenticatorpro&hl=en_US) has the same behavior as your app.
Some of my other examples are using the Share mechanism, but I don't think that's true of FolderSync.
Regardless, I'll open a Feature Request for Share (not just for OneDrive),
and I'll change this Issue to just the problem of Google Drive not appearing initially.
Thank you.

**Comment by alexbakker** [comment]
Thanks for following up and creating a proposal for that. 

The fact that Google Drive did not appear initially for you is not something we would be able to fix, unfortunately. Aegis only makes simple calls to the Storage Access Framework. The system DocumentsUi handles listing all of the DocumentProviders (in your case, that's be the cloud providers), so that's out of our hands.

**Comment by JNavas2** [comment]
With respect, I've never seen that issue with any other app,
and that it initially did not appear, and then spontaneously started appearing,
suggests some sort of initialization issue.

**Comment by alexbakker** [comment]
This is all we do when asking the user the pick a location to export to: https://github.com/beemdevelopment/Aegis/blob/94ebc0809746b44bfab5d6fcfbb9b9dc35820ca6/app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java#L642-L647. Android takes care of the rest.

**Comment by JNavas2** [comment]
You may need to do something else, because it's definitely a bug.
How I reproduced it:

1. Uninstall the app.
2. Reinstall the app.
3. Add an entry.
4. Try to Export.
5. Google Drive does _not_ appear.

![Screenshot_20200705-144333 (Custom)](https://user-images.githubusercontent.com/14850792/86542932-f15a7880-bece-11ea-8884-a158d059a581.png)

**Comment by chenningg** [comment]
I'm using Pixel 2a XL and the same issue occurs for me. I can see Google Drive and Dropbox when trying to import a file, but not when I'm trying to setup auto export with an encrypted vault. Attached are the screenshots for importing a file and exporting a vault respectively:

Importing file:
![Importing file](https://i.imgur.com/T9W89OR.png)

Exporting vault:
![Exporting vault](https://i.imgur.com/uxvBrSV.png)

Does Google Drive and Dropbox both not support the creating file intent, and only allow read only?

**Comment by alexbakker** [comment]
That's a different issue. Google Drive just doesn't support picking a folder (i.e. the ACTION_OPEN_DOCUMENT_TREE intent). When exporting the vault once with the option at the bottom (ACTION_CREATE_DOCUMENT), Google Drive should appear.

**Comment by chenningg** [comment]
Hmm. Not sure if I understand this - so manual exports are able to write into the Google Drive folder but the automated ones (export backup on change) cannot save automatically to the folder?

**Comment by JNavas2** [comment]
@chenningg 
That is correct, but irrelevant to this issue.

**Comment by JNavas2** [comment]
Please reopen this Issue, because the **bug** remains, and _does not affect other apps_. There's something specific to this app that causes the problem.

**Comment by alexbakker** [comment]
@chenningg Your understanding is correct. For exporting, we make the user select a file location, but when configuring backups, we make the user select a folder location. The latter is not yet supported by Google Drive, unfortunately.

@JNavas2  Which apps did you test?

**Comment by JNavas2** [comment]
@alexbakker 
I just tested [Authenticator Pro](https://play.google.com/store/apps/details?id=me.jmh.authenticatorpro).
Installed it, added an entry, then Menu > Backup > Menu, and Google Drive appears immediately.
Source is available on [GitHub](https://github.com/jamie-mh/AuthenticatorPro), so you can see how they are doing it.
Thank you.

![Screenshot_20200730-065717-01](https://user-images.githubusercontent.com/14850792/88933387-2fc82680-d234-11ea-8211-efb27304b8d0.jpeg)

**Comment by alexbakker** [comment]
Previously, [you reported](https://github.com/beemdevelopment/Aegis/issues/507#issuecomment-653903144) that Authenticator Pro has the same behavior as Aegis. Was that also about Google Drive not appearing initially? If so, has that now been fixed in Authenticator Pro according to you?

They're doing basically the same thing we are: https://github.com/jamie-mh/AuthenticatorPro/blob/e201789e7d448cf8a278df9167e8c9315991c38b/AuthenticatorPro/Source/Activity/MainActivity.cs#L441-L449. The only difference is the MIME type they're sending along. If that turns out to make a difference, I'll figuratively eat my hat.

Are you still able to reliably reproduce the issue in Aegis? I can build a debug APK that sets ``application/octet-stream`` as the MIME type for you to test.

**Comment by JNavas2** [comment]
@alexbakker 
I meant that Authenticator Pro exhibits the same cloud provider behavior on Backup, not that it had the same bug. Apology for not being more clear.
But no matter, as I'm not now able to reproduce this issue, not even with a different Google account, so this issue should remain Closed. Apology for not checking before whining. 
Thank you.
p.s. It's embarrassing to start the day with two apologies. :blush:

**Comment by chenningg** [comment]
@alexbakker Thanks for clarifying, however the problem remains, how should I enable automatic backups to a cloud folder of some sort? Neither Google Drive nor Dropbox appear to support said folder choosing, and they are two of the largest cloud providers around.

**Comment by alexbakker** [comment]
@chenningg Yeah, it's a real bummer that the large cloud providers don't support is. Especially Google, as they're forcing the Storage Access Framework on everyone, but then don't implement support for it in their own apps. Personally, I configured Aegis to backup the vault to local storage and have Syncthing watch that folder to sync the backups to my PC and laptop.

**Comment by JNavas2** [comment]
@chenningg 
This issue is about Export, not Auto Backup.

@alexbakker 
Yes, but if you enable Auto Backup of an encrypted vault, as I suggest [here](https://github.com/beemdevelopment/Aegis/issues/544#issuecomment-666515264) in Issue #544, then the problem is solved, no?

**Comment by chenningg** [comment]
@JNavas2 Woops, read it wrongly, I guess my issue is about auto backup instead. Guess I'll go with @alexbakker suggestion and just do manual backups on change.

**Comment by ThomasBlt** [comment]
@alexbakker Same problem here. Both in export and autobackup.
setup is brand new (first time user migrating from authy) 
In both case I can only save to my "Download" folder by default. I can enable "show internal memory" and then save anywhere but Google drive doesn't show up.

Version: 1.4.2
Source: Google Play
Vault encrypted: Yes (with biometric unlock)
Android : 10.1.0

**Comment by alexbakker** [comment]
Google Drive not showing up when configuring automatic backup is expected, because Google Drive doesn't fully participate in Android's Storage Access framework. As for it not showing up when exporting, do you have the Google Drive app installed?

**Comment by ThomasBlt** [comment]
Yes I have Google drive and it was installed before Aegis.

**Comment by chrcoluk** [comment]
Doesnt show up here, I cannot find a way to backup to the cloud, this is an issue, because if I lose my phone I lose my 2fa, it needs a cloud backup facility.

**Comment by JNavas2** [comment]
@chrcoluk 
You have two good backup options. You can use either or both.
1. Backup to a local directory and sync that local directory to the cloud.
2. Enable the option _Participate in Android's backup system_.

**Comment by chrcoluk** [comment]
I ended up using the folder sync app, its ok, but it feels bloated needing a 3rd party app to do it.  Google drive app will only backup folders if I let it backup the entire phone which I dont want it to do, and one drive app doesnt support it natively at all.  Still I have a working solution now, and thanks for implementing the root migration feature as that probably saved me a lot of hassle moving from authy. :)

**Comment by JNavas2** [comment]
[Folder Sync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite) is a good choice.

Individual files can be synced to Google Drive with the [Files by Google](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files) app, but it's a bit inflexible:
- It only supports certain file types (e.g., .txt, .zip).
- It only supports specific files, not folders.

Aegis backups fail on both counts. It would work if Aegis backed up to a constant ZIP file.
You might want to suggest that as a future improvement.
<img width="270" alt="Screenshot_20220829-071926" src="https://user-images.githubusercontent.com/14850792/187225033-b7435859-e594-4e2b-afbd-faf50ae686cb.png">
